# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pack <- function(areas) {
    .Call('ggraph_pack', PACKAGE = 'ggraph', areas)
}

circlePackLayout <- function(parent, weight) {
    .Call('ggraph_circlePackLayout', PACKAGE = 'ggraph', parent, weight)
}

partitionTree <- function(parent, order, weight, height) {
    .Call('ggraph_partitionTree', PACKAGE = 'ggraph', parent, order, weight, height)
}

cut_lines <- function(x, y, id, start_width, start_height, end_width, end_height, start_type, end_type) {
    .Call('ggraph_cut_lines', PACKAGE = 'ggraph', x, y, id, start_width, start_height, end_width, end_height, start_type, end_type)
}

pathAttr <- function(paths, ngroups) {
    .Call('ggraph_pathAttr', PACKAGE = 'ggraph', paths, ngroups)
}

splitTreemap <- function(parent, order, weight, width, height) {
    .Call('ggraph_splitTreemap', PACKAGE = 'ggraph', parent, order, weight, width, height)
}

